apiVersion: batch/v1
kind: Job
metadata:
  name: git-repo-copy-job
  namespace: jenkins
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: jenkins
      containers:
        - name: clone-repos
          image: meghdo/clone-repos:v2
          args:
          - "--source-repo"
          - "drizzle"
          - "--git-org"
          - "byngtech"
          - "--dns"
          - "breeze.com"
          - "--group"
          - "com.breeze.snow"
          - "--projectid"
          - "meghdo-4567"
          - "--project"
          - "breeze"
          - "--directory"
          - "true"
      restartPolicy: Never