image: meghdo/clone-repos:v1.9
serviceAccount: clone-repos
project_id: meghdo-4567
create_secret: false
secret:
  github_token: github-token
jobs:
-  jobName: drizzlejava
   arguments:
     source-repo: "drizzlejava"
     git-org: "byngtech"
     dns: "breeze.com"
     group: "com.breeze.snow"
     projectid: "meghdo-4567"
     project: "breeze"
     directory: "true"


