image: meghdo/clone-repos:v1.3
serviceAccount: clone-repos
project_id: meghdo-4567
create_secret: false
secret:
  github_token: github-token
jobs:
-  jobName: drizzle
   arguments:
     source-repo: "drizzle"
     git-org: "byngtech"
     dns: "breeze.com"
     group: "com.breeze.snow"
     projectid: "meghdo-4567"
     project: "breeze"
     directory: "true"
-  jobName: shared-libraries
   arguments:
     source-repo: "shared-libraries"
     git-org: "byngtech"
     dns: "breeze.com"
     group: "com.breeze.snow"
     projectid: "meghdo-4567"
     project: "breeze"
-  jobName: java17-primer
   arguments:
     source-repo: "java17-primer"
     git-org: "byngtech"
     dns: "breeze.com"
     group: "com.breeze.snow"
     projectid: "meghdo-4567"
     project: "breeze"
# Primer job addition to seed -variables
primer_seed: true
primerimage: meghdo/primer-seed:v0.2
primerepo: java17-primer
gitorg: byngtech

