{{- $secret := lookup "secrets-store.csi.x-k8s.io/v1" "SecretProviderClass" "clone-repos" "github-token" -}}
{{- if not $secret }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: github-token
  namespace: clone-repos
spec:
  {{- if eq $.Values.cloudProvider "aws" }}
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secret.github_token }}
        objectType: secretsmanager
        objectAlias: "token"
    region: {{ $.Values.aws.region }}
  secretObjects:
    - secretName: {{ .Values.secret.github_token| replace "_" "-" }}
      type: Opaque
      data:
        - objectName: "token"
          key: value
  {{- else if eq $.Values.cloudProvider "gcp" }}
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/{{ $.Values.gcp.project_id }}/secrets/{{ .Values.secret.github_token }}/versions/latest"
        path: "token"
  {{- end }}
{{- end }}