{{- if .Values.create_secret }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: github-token
  namespace: clone-repos
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.project_id }}/secrets/{{ .Values.secret.github_token }}/versions/latest"
        path: "token"
{{- end }}