{{- $serviceAccount := lookup "v1" "ServiceAccount" .Release.Namespace "clone-repos" -}}
{{- if not $serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount.name }}
  name: {{ .Release.Namespace }}
  {{- if eq $.Values.cloudProvider "aws" }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.account_no }}:role/{{ .Values.aws.account_name }}-jenkins-role
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceaccount.automount }}
{{- end }}