{{- $serviceAccount := lookup "v1" "ServiceAccount" .Release.Namespace "clone-repos" -}}
{{- if not $serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount.name }}
  name: {{ .Release.Namespace }}
  annotations:
    {{- if eq $.Values.cloudProvider "aws" }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.account_no }}:role/meghdo-jenkins-role
    {{- else if eq $.Values.cloudProvider "gcp" }}
    iam.gke.io/gcp-service-account: svc-gke@{{ .Values.gcp.project_id }}.iam.gserviceaccount.com
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceaccount.automount }}
{{- end }}