{{- $serviceAccount := lookup "v1" "ServiceAccount" .Release.Namespace "clone-repos" -}}
{{- if not $serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clone-repos
  name: {{ .Release.Namespace }}
automountServiceAccountToken: true
{{- end }}